# Settings for Bolt Article

# All options: blockcode, buttonlink, carousel, counter, definedlinks, filelink,
# handle, icons, imageposition, inlineformat, makebutton, print, reorder,
# selector, specialchars, style, tags, textdirection, underline, variable,
# removeformat, imageresize
default:
  plugins: [ blockcode, buttonlink, definedlinks, inlineformat, reorder, tags, underline, imageposition, filelink, removeformat, imageresize, carousel,textdirection, style]
  source: true
  grid:
    classname: 'article-grid'
    columns: 12
    patterns:
      '4|4|4': 'col-4 col-responsive|col-4 col-responsive|col-4 col-responsive'
      '4|8': 'col-4 col-responsive|col-8 col-responsive'
      '6|6': 'col-6 col-responsive|col-6 col-responsive'
      '8|4': 'col-8 col-responsive|col-4 col-responsive'


  # Settings for images
  # Note: The current editor can only upload / insert images if they are granted 
  # the 'upload' and 'list_files:files' permissions in `permissions.yaml`.  
  image:
    thumbnail: 1000×1000×max
plugins:
  ~
