# Settings for Bolt Article

# All options: blockcode, buttonlink, carousel, counter, definedlinks, filelink,
# handle, icons, imageposition, inlineformat, makebutton, print, reorder,
# selector, specialchars, style, tags, textdirection, underline, variable,
# removeformat, imageresize
default:
  plugins: [ blockcode, buttonlink, definedlinks, inlineformat, reorder, tags, underline, imageposition, filelink, removeformat, selector]
  source: true
  custom: 
    css: [ '/theme/Xofram/css/customAdminArticle.css' ]
  classes:
    p: 'article-paragraph w-100'
    figure: 'superposition'
    img: 'rounded mx-auto d-block img-fluid'
    h1: 'services_taital'
    h2: 'subtitle'
    h3: 'subtitle'
    h4: 'subtitle'
    h5: 'subtitle'
    h6: 'subtitle'
    div: 'article-div'
    ul: 'article-ul'
  grid:
    classname: 'row'
    columns: 12
    patterns:
      '4|4|4': 'col-12 col-lg-4 d-flex align-items-start justify-content-center flex-column|col-12 col-lg-4|col-12 col-lg-4 d-flex align-items-start justify-content-center flex-column'
      '4|8': 'col-12 col-md-4 col-lg-4 d-flex align-items-start justify-content-center flex-column|col-12 col-md-8 col-lg-8 d-flex align-items-start justify-content-center flex-column'
      '6|6': 'col-12 col-md-6 col-lg-6 d-flex align-items-start justify-content-center flex-column|col-12 col-md-6 col-lg-6 d-flex align-items-start justify-content-center flex-column'
      '8|4': 'col-12 col-md-8 col-lg-8 d-flex align-items-start justify-content-center flex-column|col-12 col-md-4 col-lg-4 d-flex align-items-start justify-content-center flex-column'

  # Settings for images
  # Note: The current editor can only upload / insert images if they are granted 
  # the 'upload' and 'list_files:files' permissions in `permissions.yaml`.  
  image:
    thumbnail: 1000×1000×max

plugins:
  ~
