homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        contentset:
            type: set
            label: Titre
            group: Paramètres
            fields:
                title:
                    label: Titre de la page première ligne
                    type: text
                text:
                    label: Titre de la page seconde ligne
                    type: text
        teaser:
            type: redactor
            label: Texte d'accroche
            group: Paramètres
    viewless: false
    singleton: true
    icon_many: "fa:home"
    icon_one: "fa:home"
    
engagements:
    name: Engagements
    slug: engagements
    singular_name: Engagement
    fields:
        teaser:
            type: redactor
            class: large
            info: Texte d'accroche
            label: Texte d'accroche
            group: Introduction
            required: true
        recipe_title:
            type: text
            class: large
            label: Titre de la section recettes
            group: Recettes
            required: true
        recipe_engagements:
            type: collection
            limit: 3
            label: Recettes
            group: Recettes
            fields:
              engagement:
                type: set
                label: Engagement
                fields:
                  title:
                      type: text
                      class: large
                      label: Titre de l'engagement
                  image:
                      type: image
                      label: Logo de l'engagement
                  paragraph:
                      type: redactor
                      class: large
                      info: Texte de l'engagement
                      label: Description de l'engagement
        earth_title:
          type: text
          class: large
          label: Titre de la section terre
          group: Terre
          required: true
        earth_engagements:
            type: collection
            limit: 3
            label: Engagements
            group: Terre
            fields:
              engagement:
                type: set
                label: Engagement
                fields:
                  title:
                      type: text
                      class: large
                      label: Titre de l'engagement
                  image:
                      type: image
                      label: Logo de l'engagement
                  paragraph:
                      type: redactor
                      class: large
                      info: Texte de l'engagement
                      label: Description de l'engagement
    show_on_dashboard: true
    singleton: true
    default_status: published
    icon_many: "fa:handshake"
    icon_one: "fa:handshake"
    record_template: 'engagements.twig'

history:
    name: Histoire
    singular_name: Histoire
    slug: histoire
    fields:
        title:
            type: text
            class: large
            label: Titre de la page
            group: Paramètres
        introduction:
            type: redactor
            class: large
            info: Texte d'introduction
            label: Introduction
            group: Introduction
        presentation:
            type: redactor
            class: large
            info: Présentation de Bocaux des champs
            label: Présentation
            group: Présentation
        demarche:
            type: set
            class: large
            info: Notre démarche
            label: Notre démarche
            group: Objectifs
            fields:
                vision:
                    type: redactor
                    class: large
                    label: Notre vision
                mission:
                    type: redactor
                    class: large
                    label: Notre mission
        atc:
            type: set
            class: large
            info: Présentation de l'association
            label: Présentation
            group: ATC45
            fields:
                logo:
                    type: image
                    class: large
                    label: logo de l'association
                paragraph:
                    type: redactor
                    class: large
                    info: Présentation de l'association
                    label: Présentation
        about:
            type: collection
            class: large
            info: Présentation des membres de l'association
            label: Qui sommes-nous
            group: Qui sommes-nous ?
            fields:
                members:
                    type: set
                    label: Membre
                    fields:
                        fullname:
                            type: text
                            class: large
                            label: Nom du membre
                        hierarchy:
                            type: text
                            class: large
                            label: Statut du membre
                        image:
                              type: image
                              label: Photo du membre
                        paragraph:
                            type: redactor
                            class: large
                            info: Présentation du membre
                            label: Présentation
        pictures:
            type: imagelist
            label: Images mises en avant
            group: Images de la page
            required: true
    show_on_dashboard: true
    singleton: true
    default_status: published
    icon_many: "fa:history"
    icon_one: "fa:history"
    record_template: 'histoire.twig'



# The 'Products' ContentType can be used to manage information about the
# products or services you (or your company, organisation) provide.

produits:
    name: Produits
    singular_name: Produit
    fields:
        title:
            type: text
            class: large
            variant: inline
            info: Nom du produit visible par les visiteurs
            label: Nom du produit
            fixture_format: '{catchPhrase}'
        image:
            type: image
        content:
            type: redactor
            info: Texte visible dans la fiche produit
            label: Texte de présentation
        price: 
            type: number
            class: large
            info: Prix du produit
            label: Prix
        ingredient:
            type: redactor
            info: La liste d'ingrédient du produit
            label: Liste d'ingrédients                   
        nutrition:
            type: redactor
            info: Les valeurs nutritionnelles pour 100g du produit
            label: Valeurs nutritionnelles pour 100g
        slug:
            type: slug
            uses: title 
            group: Meta
    show_on_dashboard: true
    default_status: published
    order: title
    icon_many: "fa:gifts"
    icon_one: "fa:gift"

videos:
    name: Videos
    singular_name: Vidéo
    fields:
        title:
            type: text
            class: large
            variant: inline
            info: Nom de la vidéo visible par les visiteurs
            label: Nom de la vidéo
            fixture_format: '{catchPhrase}'
        teaser:
            type: redactor
            label: Texte d'accroche
            info: Texte visible avant de voir la vidéo
            fixture_format: '{paragraph}'
        embedded:
            type: embed
            info: Lien vers la vidéo
            label: Lien vers la vidéo
            fixture_format: '{url}'
        slug:
            type: slug
            uses: [ title ]
            group: Meta
    taxonomy:  videosTags 
    show_on_dashboard: true
    default_status: published
    order: title
    icon_many: "fa:film"
    icon_one: "fa:film"

events:
    name: Événements
    singular_name: Événement
    slug: evenements
    fields:
        title:
            type: text
            class: large
            variant: inline
            info: Titre le l'actualité
            label: Titre
            fixture_format: '{catchPhrase}'
            group: Contenu
        pictures:
            type: image
            info: Image de l'actualité
            label: Image mise en avant
        DateStart:
            type: date
            info: Date de début de l'événement
            label: Date de début
            default: 'now'
            display: '{{ value|date(''d/m/Y'') }}'
            group: Evènement
        DateEnd:
            type: date
            info: Date de fin de l'événement
            label: Date de fin
            default: 'now'
            display: '{{ value|date(''d/m/Y'') }}'
            group: Evènement
        adresse:
            type: text
            info: Adresse de l'événement
            label: Adresse
            group: Evènement
        codePostal:
            type: text
            info: Code postal de l'événement
            label: Code postal
            group: Evènement
        Ville:
            type: text
            info: Ville de l'événement
            label: Ville
            group: Evènement
        teaser:
            type: redactor
            label: Texte d'accroche
            info: Texte d'accroche de la carte
            fixture_format: '{paragraph}'
            group: Contenu
        article:
            type: article
            class: large
            info: Contenue de l'événement
            label: Contenue de la page
            group: Contenu
    show_on_dashboard: true
    default_status: held
    order: date
    listing_sort: DateStart
    icon_many: "fa:newspaper"
    icon_one: "fa:newspaper"
    taxonomy: actus

contact:
    name: Contact
    singular_name: Contact
    fields:
        image:
            label: Image de la page
            type: image
            required: true
    viewless: false
    singleton: true
    icon_many: "fa:envelope"
    icon_one: "fa:envelope"


Options:
  name: Options
  singular_name: Option
  slug: options
  fields:
    logo:
      type: image
      info: Logo de l'entreprise
      label: Logo
      group: Logo
    productsIntro:
      type: textarea
      info: Texte d'introduction présent sur la page listing produits
      label: Texte d'introduction pour la page produits
      group: Texte pages de listing
    videosIntro:
      type: textarea
      info: Texte d'introduction présent sur la page listing vidéos
      label: Texte d'introduction pour la page vidéos
      group: Texte pages de listing
    eventsIntro:
      type: textarea
      info: Texte d'introduction présent sur la page listing évènements
      label: Texte d'introduction pour la page évènements
      group: Texte pages de listing
    emailBocaux:
      type: text
      info: Email de l'association Bocaux des champs
      label: Email Bocaux des champs
      group: Informations diverses
    adressBocaux:
      type: text
      info: Adresse de l'association Bocaux des champs
      label: Adresse Bocaux des champs
      group: Informations diverses
    emailATC45:
      type: text
      info: Email de l'entreprise ATC45
      label: Email ATC45
      group: Informations diverses
    adressATC45:
      type: text
      info: Adresse de l'entreprise ATC45
      label: Adresse ATC45
      group: Informations diverses
    qrInfoCard:
        type: textarea
        info: Texte pour le bandeau QR code présent en bas de differentes pages
        label: Texte pour le bandeau QR code
        group: Autres
    footerText:
        type: textarea
        info: Texte d'introduction présent sur le footer
        label: Texte d'introduction présent sur le footer
        group: Autres
    tva:
        type: number
        info: TVA de l'entreprise
        label: TVA
        group: Informations diverses
    actualitesIntro:
      type: textarea
      info: Texte d'introduction présent sur la page listing actualités
      label: Texte d'introduction pour la page actualités
      group: Texte pages de listing
       
  viewless: true
  singleton: true
  icon_many: "fa:cogs"
  icon_one: "fa:cogs"

# Possible field types:
#
# text - varchar(256) - input type text.
# number - double - Input field for numbers, with `mode: integer` or `mode: float`
# imagelist - text (65kb) - Input type for imagelists. Add multiple images. Useful for image sliders, galleries, etcetera.
# image - varchar(256) - image select/upload widget, stored as filename.
# file - varchar(256) - file select/upload widget, stored as filename.
# filelist - text (65kb) - Input type for a list of files. Including a description.
# embed - text (65kb) - embed widget for video and audio. Stored as JSON.
# html - text (65kb) - wysiwyg element.
# textarea - varchar(32768) - Simple, plain < textarea > field.
# markdown - varchar(32768) - wysiwyg element, which is parsed as Markdown text.
# date - datetime - date selector widget, with `mode: date` or `mode: datetime`
# email - text(65kb) - Input type for email.
# select - varchar(256) - select with predefined values
# templateselect - varchar(256) - select with template filenames
# checkbox - integer - checkbox-field which is 1 (checked) or 0 (unchecked)
# set - text (65kb) - Input type for sests. Group fields semantically into a combined set field.
# collection - text (65kb) - Input type for collections. Add multiple fields of different types. Useful for lists.
# data - text (65kb) - Read-only field, useful for storing (raw) data provided by an external source.
# hidden - text (65kb) - Regular text field, except it is hidden from the content editor.
# slug - text(65kb) - The slug for the record. Use with option `uses: [ title ]` to generate based on a title field.

# Using YAML repeated nodes
#
# YAML allows the defining of "repeated nodes". These allow you to define a 'node'
# with a 'key: &name' and referenced later with '<<: *name'
#
# Bolt allows you to define this with the special entry of '__nodes:' that itself
# won't create a ContentType, but will allow you to use it in actual ContentTypes
# to prevent repeating yourself.
#
# To achieve this, first create a key '__nodes:' and place it before your other contenttypes:
#__nodes:
#    field_defaults: &field_defaults
#        title:
#            type: text
#            class: large
#            group: main
#        slug:
#            type: slug
#            uses: title
#    template_defaults: &template_defaults
#        template:
#            type: templateselect
#            filter: '*.twig'
#            group: meta
#
# Then, as an example, you could create a ContentType with default fields, with
# an additional 'image' field.
#
#contenttypeabc:
#    name: ContentType Abc
#    slug: contenttypeabc
#    fields:
#        <<: *field_defaults
#        image:
#            type: image
#            attrib: title
#            extensions: [ gif, jpg, png ]
#        <<: *template_defaults
#    taxonomy: [ chapters ]
#    records_per_page: 10
#
# Alternatively, or additionally, you then can then create a ContentType with
# default fields, and a 'select' field, and a different 'templateselect' option.
#
#contenttypexyz:
#    name: ContentType Xyz
#    slug: contenttypexyz
#    fields:
#        <<: *field_defaults
#        selectfield:
#            type: select
#            values: [ none, foo, bar ]
#        template:
#            type: templateselect
#            filter: '*_xyz.twig'
#    taxonomy: [ tags ]
#    records_per_page: 20
