# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: Accueil
    title: Page d'accueil
    link: homepage
  - label: Nos engagements
    link: engagement
    title: Nos engagements
  - label: Notre histoire
    link: histoire
    title: Notre histoire
  - label: Nos produits
    link: produits
    title: Nos produits
  - label: Vidéos
    link: videos
    title: Vidéos
  - label: Actualités
    link: actualites
    title: Actualités
  - label: Évènements
    link: evenements
    title: Évènements
  - label: Contact
    link: contact
    title: Contact
