# This file defines the different types of taxonomies in Bolt. See the
# documentation for details: https://docs.bolt.cm/contenttypes/taxonomies
tags:
    slug: tags
    singular_slug: tag
    behaves_like: tags
    postfix: "Add some freeform tags. Start a new tag by typing a comma or space."
    allow_spaces: false
    #listing_template: tag-listing.twig #custom template
    required: false
videosTags:
    slug: videos-tags
    singular_slug: video-tag
    behaves_like: tags
    postfix: "Commencez un nouveau tag en saisissant un caractère, valider le tag en appuyant sur entrée."
    allow_spaces: false
    listing_template: videos.twig #custom template
    required: false
categories:
    name: Categories
    slug: categories
    singular_name: Category
    singular_slug: category
    behaves_like: categories
    multiple: true
    options: [ news, events, movies, music, books, life, love, fun ]
    required: false
videoCategory:
    name: Videos
    slug: Videos
    singular_name: Video
    singular_slug: Video
    behaves_like: videos
    multiple: false
    options: [ movies ]
    required: true
    default: movies   
actus:
    name: Actualites
    slug: actualites
    singular_name: Actualité
    singular_slug: actualite
    behaves_like: actualités
    multiple: false
    options: [ post, évènement ]
    required: true
